version: '3.4'

services:
  gerenciamentotarefas:
    image: ${DOCKER_REGISTRY-}gerenciamentotarefas
    build:
      context: .
      dockerfile: GerenciamentoTarefas/Dockerfile      
    ports:
      - "8090:8080"
      - "8091:8081"
    depends_on:
        - rabbitmq
        - mongo
    env_file:
      - .env

  workerprocessartarefa:
    image: ${DOCKER_REGISTRY-}workerprocessartarefa
    build:
      context: .
      dockerfile: WorkerProcessarTarefa/Dockerfile
    depends_on:
        rabbitmq:
         condition: service_healthy 
    env_file:
      - .env
    restart: always

  mongo:
    image: mongo:8.0 
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017" 
    environment:
      MONGO_INITDB_ROOT_USERNAME: root 
      MONGO_INITDB_ROOT_PASSWORD: password 
    volumes:
      - mongo-data:/data/db 
      - mongo-config:/data/configdb 

  rabbitmq:
    container_name: rabbitmq-server
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  mongo-data:
    driver: local
  mongo-config:
    driver: local

